title: Sandipan Roy
description: "Take it Easy; Make it Easy;"
author:
  name: "Sandipan Roy"
  email: "sandipan@parrotsec.org"
  url: "https://www.sandipan.ml"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Sandipan Roy"
year : "2020"
